# Generated by Django 3.0 on 2022-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_poem_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='place',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
