# Generated by Django 3.0 on 2022-05-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_word_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='place',
            field=models.IntegerField(),
        ),
    ]
