# Generated by Django 3.0 on 2022-05-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220524_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='place',
            new_name='xcoordinate',
        ),
        migrations.AddField(
            model_name='word',
            name='ycoordinate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
